enable_language(OBJCXX)
set(CMAKE_OBJCXX_STANDARD ${CMAKE_CXX_STANDARD})
set(CMAKE_OBJCXX_STANDARD_REQUIRED ON)
find_library(SECURITY_FRAMEWORK Security)
find_library(APPKIT_FRAMEWORK AppKit)
find_library(CARBON_FRAMEWORK Carbon)
set(PLATFORM_SOURCES include/sys/macos/MacOS.h src/sys/macos/MacOS.cpp src/sys/macos/AutoRun.cpp src/sys/macos/UrlScheme.cpp src/sys/macos/SystemProxy.cpp src/sys/macos/TrayIcon.mm src/sys/macos/GlobalHotkeys.cpp)
set(PLATFORM_LIBRARIES ${SECURITY_FRAMEWORK} ${APPKIT_FRAMEWORK} ${CARBON_FRAMEWORK})